platform :ios, '12.0'

flutter_application_path = '/Users/hjwjo/Desktop/fromBirth/flutter'

load File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'Flutter', :path => File.join(flutter_application_path, 'bin', 'cache', 'artifacts', 'engine', 'ios')
  pod 'file_picker', :path => '../.flutter/ios/Flutter'


  target 'RunnerTests' do
    inherit! :search_paths
  end
end
